tyoubo_project/tyoubo_app/urls.py
from django.urls import path
from tyoubo_app import views

app_name = 'tyoubo_app'
urlpatterns = [
    path('regist_item/', views.create_item, name='create_item'),  # 作成
    path('edit_item/<int:post_id>/', views.edit_item, name='edit_item'),  # 修正
    path('show_item/', views.read_item, name='show_item'),   # 一覧表示
    path('delete_item/<int:post_id>/', views.delete_item, name='delete_item'),   # 削除
]

tyoubo_project/tyoubo_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('tyoubo_app.urls')),
    path('admin/', admin.site.urls),
]

tyoubo_project/tyoubo_app/models.py
from django.db import models
from django import forms

# Create your models here.
class ItemModel(models.Model):
    choices = (
                    ('mustitem', '必需品'),
                    ('notmustitem', '娯楽品'),
                )
    name = models.CharField('itemname', max_length=200)
    price = models.IntegerField('price', max_length=140, blank=True)
    type = models.CharField('type', max_length=30, choices=choices)
    date = models.DateField('date', max_length=1000)

tyoubo_project/tyoubo_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.forms import ModelForm
from tyoubo_app.models import ItemModel


def create_item(request):
    """
    新たなデータを作成する
    """
    post = ItemModel()
    if request.method == 'GET':
        form = RegistItemForm(instance=post)
        return render(request, 'tyoubo_app/item_regist_page.html', {'form': form})
    if request.method == 'POST':
        form = RegistItemForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
        return redirect('tyoubo_app:read_item')

def read_item(request):
    """
    データの一覧を表示する
    """
    items = ItemModel.objects.all().order_by('id')
    return render(request,'tyoubo_app/tyoubo_page.html', {'items': items})  # Template に渡すデータ

def edit_item(request, post_id):
    """
    対象のデータを編集する
    """
    post = get_object_or_404(ItemModel, pk=post_id)
    if request.method == 'GET':
        form = RegistItemForm(instance=post)
        return render(request, 'tyoubo_app/item_regist_page.html', {'form': form, 'post_id': post_id})  # Template に渡すデータ
    elif request.method == 'POST':
        form = RegistItemForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
        return redirect('tyoubo_app:tyoubo_page.html')

def delete_item(request, post_id):
    post = get_object_or_404(ItemModel, pk=post_id)
    post.delete()
    return redirect('tyoubo_app:tyoubo_page.html')

class RegistItemForm(ModelForm):
    """
    フォーム定義
    """
    class Meta:
        model = ItemModel
        fields = ('name', 'price', 'type', 'date')

tyoubo_project/tyoubo_app/templates/tyoubo_app/item_regist_page.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Post Form</title>
</head>
<body>
    <h4>Post の編集</h4>
    {% if post_id %}
    <form action="{% url 'tyoubo_app:edit_item' post_id=post_id %}" method="post">
    {% else %}
    <form action="{% url 'tyoubo_app:create_item' %}" method="post">
    {% endif %}
      {% csrf_token %}
      {{ form }}
          <button type="submit">送信</button>
    </form>
    <a href="{% url 'tyoubo_app:show_item' %}">戻る</a>
</body>
</html>

tyoubo_project/tyoubo_app/templates/tyoubo_app/tyoubo_page.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Post lists</title>
</head>
<body>
  <table>
    <thead>
      <tr>
        <th>名前</th>
        <th>値段</th>
        <th>種類</th>
        <th>使用日</th>
      </tr>
    </thead>
    <tbody>
      {% for item in items %}
      <tr>
        <th>{{ item.itemname }}</th>
        <td>{{ item.price }}</td>
        <td>{{ item.type }}</td>
        <td>{{ item.date }}</td>
        <td>
          <a href="{% url 'tyoubo_app:edit_item' post_id=item.id %}">修正</a>
          <a href="{% url 'tyoubo_app:delete_item' post_id=item.id %}">削除</a>
        </td>
      </tr>
      {% empty %}
      <tr>
        <th>登録商品はなしです</th>
        <td>--</td>
        <td>--</td>
        <td>--</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'tyoubo_app:create_item' %}">作成</a>
</body>
</html>